# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
    push:
        branches:
            - main
        paths-ignore:
            - '**.md'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: yarn install
            #- run: yarn test

    publish-gpr:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  registry-url: https://npm.pkg.github.com/
            - run: git config --global user.email "ross@bsoltec.com"
            - run: git config --global user.name "Ross Chiu"
            - run: yarn install
            - run: yarn build
            - run: yarn version --patch
            - run: git push --tags && npm publish . && git push && echo \"Successfully released version $npm_package_version!\"
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    delete-old:
        needs: publish-gpr
        runs-on: ubuntu-latest
        steps:
            - uses: actions/delete-package-versions@v3
              with:
                  package-name: 'express-advanced-query'
